apiVersion: v1
kind: Service
metadata:
  name: eks-example-mkt
  namespace: eks-example-mkt
  labels:
    app: eks-example-mkt
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: eks-example-mkt
